name: push_on_master_without_pr
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  test:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # if: github.event.pull_request == null
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.before == github.event.after
    # if: github.ref == 'refs/heads/master'
    if: github.event.before == github.event.after
    strategy:
      matrix:
        # disabling windows-latest for now. zig fmt --check gives strange results
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
      - run: |
          echo PR #${{ github.event.number }} test2 `zig version`
  mkdocs-gh-deploy:
    if: needs.test.result == 'success' || needs.test.result == 'skipped'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: echo PR #${{ github.event.number }} mkdocs-gh-deploy #${{ needs.test.result }}
