name: Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} test1
