name: push_on_master
on:
  push:
    branches:
      - master
  # pull_request_target:
  #   types:
  #     - closed
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: |
          if [ -z "${{ steps.PR.outputs.number }}" ]; then
            echo "PR=false" >> $GITHUB_OUTPUT
            echo Not a PR
            echo "MERGE_FROM_PULL_REQUEST=false" >> $GITHUB_ENV
          else
            echo Is a PR
            echo "MERGE_FROM_PULL_REQUEST=true" >> $GITHUB_ENV
            echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
          fi
  mkdocs-gh-deploy:
    needs: test
    if: needs.test.result == 'success' || needs.test.result == 'skipped'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: echo PR #${{ github.event.number }} mkdocs-gh-deploy #${{ needs.test.result }}
