name: push_on_master
on:
  push:
    branches:
      - master
  # pull_request_target:
  #   types:
  #     - closed
permissions:
  contents: write
jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Set the value
        id: step_one
        shell: bash
        run: |
          # bash
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "State is: '${{ env.action_state }}'" # No output since same step

      - name: Use the value
        id: step_two
        shell: bash
        run: |
          # bash
          echo "Action State is: '${{ env.action_state }}'" # Output works

  use_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Use the value again 1
        id: step_two1
        run: |
          echo "Sleep State 1 is ${{ env.sleep_state1 }}" # Output works
