name: push_on_master_without_pr
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    branches:
      - master
permissions:
  contents: write
jobs:
  test:
    # github.ref == 'refs/heads/master'
    # if: github.event_name == 'push' && github.event.pull_request == null
    strategy:
      matrix:
        # disabling windows-latest for now. zig fmt --check gives strange results
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
      - run: |
          echo PR #${{ github.event.number }} test2 `zig version`
