name: push_on_master
on:
  push:
    branches:
      - master
  # pull_request_target:
  #   types:
  #     - closed
permissions:
  contents: write
jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Set the value
        id: step_one
        shell: bash
        run: |
          # bash
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "State is: '${{ env.action_state }}'" # No output since same step

      - name: Use the value
        id: step_two
        shell: bash
        run: |
          # bash
          echo "Action State is: '${{ env.action_state }}'" # Output works

  build_windows_latest:
    runs-on: windows-latest

    steps:
      - name: Set the value1
        id: step_one1
        run: |
          # powershell
          Add-Content -Path ${env:GITHUB_ENV} -Value "sleep_state1=red"
          # No output since same step
          echo "Sleep State 1 is ${{ env.sleep_state1 }}"

      - name: Set the value2
        id: step_one2
        shell: cmd
        run: |
          rem windows command
          printf "sleep_state2=purple" >> %GITHUB_ENV%
          rem No output since same step
          printf "Sleep State 2 is ${{ env.sleep_state2 }}"

      - name: Use the value again 1
        id: step_two1
        run: |
          # powershell
          echo "Sleep State 1 is ${{ env.sleep_state1 }}" # Output works
          echo "Sleep State 2 is ${{ env.sleep_state2 }}" # Output works

      - name: Use the value again 2
        id: step_two2
        shell: cmd
        run: |
          rem windows command
          rem Output works
          printf "Sleep State 1 is ${{ env.sleep_state1 }}\n"
          rem Output works
          printf "Sleep State 2 is ${{ env.sleep_state2 }}\n"
